version: "3.8"

services:
  server:
    image: node:18.14-alpine3.17
    container_name: server
    build:
      context: ./server
    command: sh ./entrypoint.sh
    working_dir: /app
    volumes:
      - ./server/:/app
    ports:
      - 8000:8000
    env_file: ./server/.env
    environment:
      - MONGO_PATH=scrabbledb.t7nrpcq.mongodb.net/ScrabbleDB?retryWrites=true

  client:
    image: node:18.14-alpine3.17
    build:
      context: ./client
    command: sh ./entrypoint.sh
    working_dir: /app
    volumes:
      - ./client/:/app
    ports:
      - 5173:5173
