version: "3.8"

services:
  server:
    image: node:18.14-alpine3.17
    container_name: server
    build: ./server
    command: sh ./entrypoint.sh
    working_dir: /app
    volumes:
      - ./server/:/app
    ports:
      - 8000:8000
    env_file: ./server/.env
    environment:
      - MONGO_PATH=scrabbledb.t7nrpcq.mongodb.net/ScrabbleDB?retryWrites=true

  client:
    image: node:18.14-alpine3.17
    container_name: client
    build: ./client
    command: sh ./entrypoint.sh
    working_dir: /app
    volumes:
      - ./client/:/app
    ports:
      - 5173:5173

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev --import-realm --db postgres  \
      --db-url jdbc:postgresql://postgres/keycloak --db-username=keycloak --db-password=keycloak
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

  postgres:
    image: postgres:15.2-alpine3.17
    container_name: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    ports:
      - 5432:5432
