apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:latest
          args: ["start-dev"]
          resources:
            limits:
              memory: "1Gi"
              cpu: "2000m"
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: wordgame-secret
                  key: keycloak-admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordgame-secret
                  key: keycloak-password
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: wordgame-config
                  key: db-url
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wordgame-secret
                  key: postgres-user
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordgame-secret
                  key: postgres-password
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: LoadBalancer
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080
